# Generated by Django 2.2.1 on 2019-08-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unltd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(db_column='db_id', primary_key=True, serialize=False)),
                ('filename', models.CharField(db_column='filename', max_length=255)),
                ('filesize', models.CharField(db_column='size', max_length=255)),
                ('process', models.CharField(db_column='process', default=None, max_length=20)),
                ('created_date', models.DateTimeField(db_column='created_date')),
            ],
            options={
                'db_table': 'backup',
                'managed': True,
            },
        ),
    ]
