# Generated by Django 2.2.1 on 2019-08-05 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unltd', '0003_auto_20190805_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorStaff',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='unltd.User')),
            ],
            options={
                'db_table': 'VendorStaff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VendorMember',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('userid', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='unltd.User')),
            ],
            options={
                'db_table': 'VendorMember',
                'managed': True,
            },
        ),
    ]
