# Generated by Django 2.2.1 on 2019-08-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unltd', '0007_auto_20190806_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Google_Setup',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('mapapi', models.CharField(db_column='Map_API', max_length=225)),
                ('recaptchaapi', models.CharField(db_column='ReCaptcha_API', max_length=225)),
                ('analyticCode', models.CharField(db_column='Analytic_Code', max_length=225)),
            ],
            options={
                'db_table': 'Google_Setup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment_Gateway',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('mailpaypal', models.CharField(db_column='Paypal_Mail', default=None, max_length=225)),
                ('mailStripe', models.CharField(db_column='Strip_Mail', default=None, max_length=225)),
                ('NameBank', models.CharField(db_column='Bank_Name', default=None, max_length=225)),
                ('NameAcc', models.CharField(db_column='Account_Name', default=None, max_length=225)),
                ('AccNo', models.CharField(db_column='Account_Number', default=None, max_length=225)),
                ('IbanNo', models.CharField(db_column='IBAN_Number', default=None, max_length=225)),
                ('CreditNo', models.CharField(db_column='Credit_Card_No', default=None, max_length=225)),
                ('Type', models.CharField(db_column='Type', default=None, max_length=225)),
                ('Status', models.CharField(db_column='Status', default=None, max_length=225)),
            ],
            options={
                'db_table': 'Payment_Gateway',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SMS_Setup',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('servicename', models.CharField(db_column='ServiceName', max_length=225)),
                ('apikey', models.CharField(db_column='Api_key', max_length=225)),
                ('costtovendor', models.IntegerField(db_column='CostToVendor', default=None)),
                ('refill', models.IntegerField(db_column='MinimumRefill', default=None)),
                ('rechargealert', models.IntegerField(db_column='RechargeAlert', default=None)),
                ('Status', models.CharField(db_column='Status', default=None, max_length=225)),
            ],
            options={
                'db_table': 'SMS_Setup',
                'managed': True,
            },
        ),
    ]
